### ISSUE TITLE
[Bug]: Various types of System.InvalidOperationException thrown at shut-down.

### ISSUE THREAD

**Issue by sniggyfigbat** [Yucked/Victoria#126]
### Describe your issue in as much detail as possible

When I shut down my .NET program, Victoria seems to throw exceptions.
- If Lavalink isn't connected: `System.InvalidOperationException: "Can't disconnect when client isn't connected."`
- If Lavalink is successfully connected (regardless of whether in use): `System.InvalidOperationException: "WebSocket is not in open state. Current state: CloseSent"`.

The program is a pretty straightforward .NET setup, using Victoria pretty close to the examples but with a few extra features. The exceptions get thrown when shutting down by pressing `Ctrl-C` in the console, and get thrown at the `IHost` run line:
```
var host = builder.Build();
await host.RunAsync(); // Exceptions thrown to here.
```

It's entirely possible that this is user-error on my end, but I'm not spotting any safe-shutdown-related code in the v5 example that I might have missed. Interestingly, I just discovered that .NET doesn't seem to call `IDisposable` on services on shutdown if the program is ended abruptly by closing the console window, which may be why more people haven't encountered this.

---

### When Lavalink *isn't* connected

![image](https://user-images.githubusercontent.com/3359069/155843498-32ab37a1-51ec-4d41-b3a4-6a00d4709f19.png)

Full stack trace for "Can't disconnect when client isn't connected.":
```
   at Victoria.LavaNode`1.<DisconnectAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Victoria.LavaNode`1.<DisposeAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<<DisposeAsync>g__Await|22_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<<DisposeAsync>g__DisposeAsync|16_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MYPROGRAMNAME.Program.<Main>d__0.MoveNext() in D:\Documents\Misc\MYPROGRAMNAME\Program.cs:line 81
```

---

### When Lavalink *is* connected

![image](https://user-images.githubusercontent.com/3359069/155842959-a709104c-2000-4c76-986d-735442644df1.png)

Full stack trace for "WebSocket is not in open state. Current state: CloseSent":
```
   at Victoria.LavaSocket.<DisconnectAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Victoria.LavaNode`1.<DisconnectAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Victoria.LavaNode`1.<DisposeAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<<DisposeAsync>g__Await|22_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<<DisposeAsync>g__DisposeAsync|16_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MYPROGRAMNAME.Program.<Main>d__0.MoveNext() in D:\Documents\Misc\MYPROGRAMNAME\Program.cs:line 81
```

### Version

v5 (Latest)

### Version

GitHub's latest

**Comment by Yucked** [comment]
- If Lavalink isn't connected: `System.InvalidOperationException: "Can't disconnect when client isn't connected."`

That happens if disconnect is called when you have already disconnected from Lavalink.

- If Lavalink is successfully connected (regardless of whether in use): `System.InvalidOperationException: "WebSocket is not in open state. Current state: CloseSent".`

If Victoria is connected to Lavalink then that error shouldn't happen but if you disconnected and tried performing any operation or the send queue wasn't empty then that could happen.


ASP.NET does expose a way to take care of this and you can combine it with Victoria to handle disconnects gracefully. Use the `Lavalink.IsConnected` property to check whether you're connected before calling `DisconnectAsync` or `DisposeAsync` in conjunction with https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime.applicationstopping?view=aspnetcore-6.0

**Comment by Yucked** [comment]
Gonna close this issue since no response.
