### ISSUE TITLE
[ BUG ] GetPlayer&TryGetPlayer fails with KeyNotFoundException

### ISSUE THREAD

**Issue by asteria121** [Yucked/Victoria#139]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

GetPlayer & TryGetPlayer fails and throw exception like stacktrace below.

I wrote code with DiscordShardedClient instead of DiscordSocketClient. I also add _lavaNode.ConnectAsync() on ShardReady event. I called GetPlayer with "_lavaNode.GetPlayer(Context.Guild);".
Is there any problem with my code or need more information about my code?

### `Stacktrace / Screenshots`
![1](https://user-images.githubusercontent.com/24371508/213879537-af174f83-9f2a-46bf-8bf8-bb44a2a812e4.png)
Dependency Injection code

Exception thrown
System.Collections.Generic.KeyNotFoundException: The given key '936820198726565949' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at IrisBot.Modules.CommandModule.PlayMusic(String query) in D:\Develop\IrisBot\IrisBot\Modules\CommandModule.cs:line 0
   at Discord.Interactions.Builders.ModuleClassBuilder.<>c__DisplayClass11_0.<<CreateCallback>g__ExecuteCallback|1>d.MoveNext()

936820198726565949 is my guild id. I test my slashcommand on this guild.

**Comment by asteria121** [comment]
+ Victoria 5.2.5, Discord.NET 3.9.0
