### ISSUE TITLE
Got error while searching youtube song

### ISSUE THREAD

**Issue by Nothing-Just-a-Code** [Yucked/Victoria#46]
When i run search code i got this error

Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error reading JObject from JsonReader. Path '', line 0, position 0.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Victoria.LavaRestClient.<SearchTracksAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Discord_Bot.Form1.VB$StateMachine_23_Button1_Click.MoveNext() in C:\Users\Huntsman\Documents\Visual Studio 2019\Projects\Discord Bot - Copy\Discord Bot\Form1.vb:line 167

**Comment by Yucked** [comment]
Hey another user reported that error few minutes ago. For them it was a matter of incorrect password I believe. Set Victoria's log severity to debug and let me know what it reports when you search for a song again and also post lavalink logs.
