### ISSUE TITLE
[ BUG ] SearchAsync always returning NoMatches

### ISSUE THREAD

**Issue by collectVood** [Yucked/Victoria#64]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

This could be related to my lavalink possibly but for some reason when using SearchAsync(someQuery); its loadstatus is always NoMatches. When using SearchYouTubeAsync(someQuery); this seems to not occur. 

In other relations it seems like I am doing something wrong when trying to load a playlist too from youtube. Always get the `Could not find tracks from mix.` or ` Something went wrong when looking up the track` exception when using SearchYoutubeAsync and a query which consists of a link to a playlist. This could also relate to LavaLink though...

**Comment by Yucked** [comment]
Does lavalink say anything in console when that happens?

And iirc SearchAsync is used for links. I might be wrong about that.

**Comment by collectVood** [comment]
Oh yeah an error, forgot to add that.

`Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (org.apache.http.client.entity.LazyDecompressingInputStream); line: 2, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2654) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:856) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753) ~[jackson-core-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231) ~[jackson-databind-2.10.0.jar!/:2.10.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2692) ~[jackson-databind-2.10.0.jar!/:2.10.0]
        at com.sedmelluq.discord.lavaplayer.tools.JsonBrowser.parse(JsonBrowser.java:178) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubePlaylistLoader.load(DefaultYoutubePlaylistLoader.java:40) ~[lavaplayer-1.3.34.jar!/:na]
        ... 14 common frames omitted
`

Also have been trying SearchAsync on links seems to yield the same result.

**Comment by collectVood** [comment]
And for the `Could not find tracks from mix` I get this error:

`
2020-03-03 17:09:42.684 ERROR 1340 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Could not find tracks from mix.
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeMixProvider.loadMixWithId(YoutubeMixProvider.java:99) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:249) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.mix(YoutubeAudioSourceManager.java:228) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:91) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:61) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:196) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:133) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[lavaplayer-1.3.34.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[lavaplayer-1.3.34.jar!/:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_231]
`

Formatting not working on this one for some reason, sorry.

**Comment by Yucked** [comment]
That seems like a Lavalink failing to parse the JSON. So either something broke in Lavalink/LavaPlayer or the response returned from those sites has changed.

**Comment by Yucked** [comment]
I'm guessing this issue got resolved? I'd be closing this now.

**Comment by jihadkhawaja** [comment]
[Command]	/play omfg hello
[LAVALINK]	2020-10-30 01:58:28.567  INFO 4184 --- [ XNIO-1 task-48] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
[LAVALINK]	2020-10-30 01:58:29.478  WARN 4184 --- [ader-2-thread-1] c.s.d.l.s.youtube.YoutubeSearchProvider  : Failed to match ytInitialData JSON object
[LAVALINK]	2020-10-30 01:58:29.479  INFO 4184 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : No matches found

**Comment by Yucked** [comment]
?????

**Comment by jihadkhawaja** [comment]
> ?????

Search always returning null, sometimes it works after retrying for more than 20 times, then it give same error again, what could be the isssue ?

**Comment by Yucked** [comment]
That's a Lavalink issue sadly. If Lavalink doesn't return anything, Victoria won't show anything.

**Comment by jihadkhawaja** [comment]
For anyone having the same issue, I solved it by downgrading to [OpenJDK 13](https://www.oracle.com/java/technologies/javase-jdk13-downloads.html) and updating [Lavalink](https://github.com/Frederikam/Lavalink/releases)
