### ISSUE TITLE
[ BUG ] NullReferenceException on PlayAsync

### ISSUE THREAD

**Issue by cxnky** [Yucked/Victoria#83]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`

When calling PlayAsync with a track (which has full information specified), I get a NullReferenceException

### `Stacktrace / Screenshots`

```
   at Victoria.LavaSocket.<SendAsync>d__23`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Victoria.LavaPlayer.<PlayAsync>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Asphalt.Modules.Audio.<Play>d__3.MoveNext() in D:\Development\AsphaltV4\Asphalt.Modules\Audio.cs:line 102
```

Line 102 is ``await player.PlayAsync(track);``

track is the following:
![image](https://i.imgur.com/NtgKVMP.png)

This happens on all tracks that I try

**Comment by Yucked** [comment]
Have you checked whether the LavaPlayer is null?

**Comment by cxnky** [comment]
I just double checked the docs, I forgot to call ConnectAsync on the node
