### ISSUE TITLE
[ BUG ] WebSocket is not in an open state

### ISSUE THREAD

**Issue by cxnky** [Yucked/Victoria#98]
<p align="center">
<img src="https://media.giphy.com/media/20JY76TfKAhR20SfJu/source.gif" width="25%"/>
</p>

---

### `Describe the bug/issue.`
Every so often when someone tries to play something, Victoria will just come back with the error 

"WebSocket is not in an open state. Current state: None". 

This happens completely randomly, only happens on my actual bot - not when running locally or anything. 

*Please provide as many details as possible. Such as line number, file name, if the bug is reproducible, etc.*

### `Stacktrace / Screenshots`
```at Victoria.LavaSocket.SendAsync[T](T value)
   at Victoria.LavaPlayer.StopAsync()
   at Asphalt.Services.Audio.AudioService.ForceDisconnect(UInt64 userID, UInt64 guildID) in /opt/build/Asphalt.Services/Audio/AudioService.cs:line 179
   at Asphalt.Modules.Audio.Stop() in /opt/build/Asphalt.Modules/Audio.cs:line 730
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   at Discord.Commands.CommandInfo.<>c__DisplayClass44_0.<<ExecuteAsync>b__0>d.MoveNext()```

*When debugging yourself, you can attach screenshots of Autos/Locals tabs in Visual Studio.*

**Comment by Gameoholic** [comment]
I've had this happen to me as well.
I wrote this code so that if a track is playing, it will skip it and replace it with another track (assume there is only 1 track in the queue at a time):
```
            if (player.PlayerState == PlayerState.Playing)
            {
                Log.Info($"Enqueued {track.Title} and skipped {player.Track.Title}");
                player.Queue.Enqueue(track);
                await player.SkipAsync();
                Log.Info($"Playing {track.Title}");
            }
            else
            {
                await player.PlayAsync(track);
                Log.Info($"Playing {track.Title}");
            } 
```

The problem arises when a track is already playing. So it does enqueue it and skip the current one, but upon trying to play the new track I get the following error:
WebSocket is not in open state. Current state: None

**Comment by Yucked** [comment]
What version of Victoria are you using?

**Comment by cxnky** [comment]
5.2.1

**Comment by Gameoholic** [comment]
The same issue happens when using version 5.2.2.

**Comment by Yucked** [comment]
Can you please try 5.2.3 and see if the issue persists?

**Comment by Yucked** [comment]
Closing this, if the issue arises again please feel free to reopen.

**Comment by cxnky** [comment]
Still getting the error on 5.2.3, 

[14:06:22 INF] [Lavalink] System.NullReferenceException: Object reference not set to an instance of an object.
   at Victoria.LavaNode`1.OnDataAsync(Byte[] data)
   at Victoria.LavaSocket.ReceiveAsync()

**Comment by Yucked** [comment]
what line?
